# Generated by Django 5.0.4 on 2024-07-22 23:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillrating',
            name='user',
        ),
        migrations.AddField(
            model_name='skillrating',
            name='rating',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_sport', to='api.sport')),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='skills',
            field=models.ManyToManyField(to='api.skill'),
        ),
        migrations.AlterField(
            model_name='skillrating',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.skill'),
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
