# Generated by Django 5.0.4 on 2024-07-23 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_skillrating_user_skillrating_rating_skill_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='description',
            new_name='name',
        ),
    ]
