# Generated by Django 5.0.4 on 2024-07-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_description_skill_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillrating',
            name='current_average',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='skillrating',
            name='rating_times',
            field=models.BigIntegerField(default=0),
        ),
    ]
