# Generated by Django 5.0.4 on 2024-07-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_skillrating_current_average_skillrating_rating_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='skills',
        ),
        migrations.AddField(
            model_name='player',
            name='nick_name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
