# Generated by Django 5.0.4 on 2024-08-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_player_skills_player_nick_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillrating',
            old_name='rating_times',
            new_name='dislike',
        ),
        migrations.RemoveField(
            model_name='skillrating',
            name='rating',
        ),
        migrations.AddField(
            model_name='skillrating',
            name='like',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skillrating',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
