# Generated by Django 5.0.4 on 2024-08-13 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_rating_times_skillrating_dislike_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillrating',
            name='current_average',
        ),
    ]
